export const traductions = {
  fr: {
    // Général
    chantpro: "ChantPro",
    retour: "← Retour",
    ajouter: "Ajouter",
    annuler: "Annuler",
    supprimer: "Supprimer",
    modifier: "Modifier",
    fermer: "Fermer",

    // Page d'accueil
    slogan: "Gérez vos chantiers simplement",
    commencer: "Commencer gratuitement",
    chantiers: "Chantiers",
    chantiersDesc: "Suivez tous vos chantiers en temps réel",
    heures: "Heures",
    heuresDesc: "Pointage simple pour chaque employé",
    messagerie: "Messagerie",
    messagerieDesc: "Communiquez avec toute votre équipe",

    // Navigation
    accueil: "Accueil",
    planning: "Planning",
    messages: "Messages",
    photos: "Photos",
    employes: "Employés",

    // Connexion
    connexion: "Connectez-vous à votre espace",
    emailOuTelephone: "Email (patron) ou Téléphone (employé)",
    motDePasseOuPin: "Mot de passe ou Code PIN",
    seConnecter: "Se connecter",
    commentAppeler: "Comment voulez-vous être appelé ?",
    erreurConnexion: "Email/téléphone ou mot de passe/PIN incorrect",

    // Dashboard
    bonjour: "Bonjour",
    chantiersActifs: "Chantiers actifs",
    chantiersEnCours: "Chantiers en cours",
    enCours: "En cours",
    enPause: "En pause",
    termine: "Terminé",

    // Chantiers
    nouveauChantier: "Nouveau chantier",
    nomChantier: "Nom du chantier",
    adresse: "Adresse",
    client: "Client",
    responsable: "Responsable",
    raison: "Raison (optionnel)",
    ajouterChantier: "+ Ajouter un chantier",
    ajouterUneRaison: "Ajouter une raison...",

    // Employés
    nouvelEmploye: "Nouvel employé",
    prenom: "Prénom",
    nom: "Nom",
    role: "Rôle",
    telephone: "Téléphone",
    codePin: "Code PIN (4 chiffres)",
    ajouterEmploye: "+ Ajouter un employé",
    permissions: "Permissions",
    peutModifierPlanning: "Peut modifier le planning",
    peutSupprimerEmployes: "Peut supprimer des employés",
    peutGererChantiers: "Peut gérer les chantiers",

    // Planning
    planningSemaine: "Planning de la semaine",
    nouvelleEntree: "Nouvelle entrée",
    choisirEmploye: "Choisir un employé",
    choisirChantier: "Choisir un chantier",
    semainePrecedente: "← Semaine précédente",
    semaineSuivante: "Semaine suivante →",
    revenirAujourdhui: "Revenir à aujourd'hui",
    prevu: "Prévu",
    realise: "Réalisé",
    aucuneEntreeJour: "Aucune entrée pour ce jour",
    lundi: "Lundi",
    mardi: "Mardi",
    mercredi: "Mercredi",
    jeudi: "Jeudi",
    vendredi: "Vendredi",
    samedi: "Samedi",
    dimanche: "Dimanche",

    // Messagerie
    nouveauMessage: "+ Nouveau message",
    choisirDestinataire: "Choisir un destinataire :",
    ecrireMessage: "Écrire un message...",
    envoyer: "Envoyer",
    connecte: "Connecté",
    patron: "Patron",

    // Photos
    galeriePhotos: "📷 Galerie photos",
    aucunePhoto: "Aucune photo pour le moment",
    toutesLesPhotos: "Toutes les photos",
    par: "Par",
  },

  en: {
    chantpro: "ChantPro",
    retour: "← Back",
    ajouter: "Add",
    annuler: "Cancel",
    supprimer: "Delete",
    modifier: "Edit",
    fermer: "Close",

    slogan: "Manage your construction sites easily",
    commencer: "Get started for free",
    chantiers: "Sites",
    chantiersDesc: "Track all your sites in real time",
    heures: "Hours",
    heuresDesc: "Simple time tracking for each employee",
    messagerie: "Messaging",
    messagerieDesc: "Communicate with your whole team",

    accueil: "Home",
    planning: "Schedule",
    messages: "Messages",
    photos: "Photos",
    employes: "Employees",

    connexion: "Sign in to your account",
    emailOuTelephone: "Email (manager) or Phone (employee)",
    motDePasseOuPin: "Password or PIN code",
    seConnecter: "Sign in",
    commentAppeler: "What should we call you?",
    erreurConnexion: "Incorrect email/phone or password/PIN",

    bonjour: "Hello",
    chantiersActifs: "Active sites",
    chantiersEnCours: "Sites in progress",
    enCours: "In progress",
    enPause: "On hold",
    termine: "Completed",

    nouveauChantier: "New site",
    nomChantier: "Site name",
    adresse: "Address",
    client: "Client",
    responsable: "Manager",
    raison: "Reason (optional)",
    ajouterChantier: "+ Add a site",
    ajouterUneRaison: "Add a reason...",

    nouvelEmploye: "New employee",
    prenom: "First name",
    nom: "Last name",
    role: "Role",
    telephone: "Phone",
    codePin: "PIN code (4 digits)",
    ajouterEmploye: "+ Add an employee",
    permissions: "Permissions",
    peutModifierPlanning: "Can edit the schedule",
    peutSupprimerEmployes: "Can delete employees",
    peutGererChantiers: "Can manage sites",

    planningSemaine: "Weekly schedule",
    nouvelleEntree: "New entry",
    choisirEmploye: "Choose an employee",
    choisirChantier: "Choose a site",
    semainePrecedente: "← Previous week",
    semaineSuivante: "Next week →",
    revenirAujourdhui: "Back to today",
    prevu: "Planned",
    realise: "Done",
    aucuneEntreeJour: "No entry for this day",
    lundi: "Monday",
    mardi: "Tuesday",
    mercredi: "Wednesday",
    jeudi: "Thursday",
    vendredi: "Friday",
    samedi: "Saturday",
    dimanche: "Sunday",

    nouveauMessage: "+ New message",
    choisirDestinataire: "Choose a recipient:",
    ecrireMessage: "Type a message...",
    envoyer: "Send",
    connecte: "Connected",
    patron: "Manager",

    galeriePhotos: "📷 Photo gallery",
    aucunePhoto: "No photos yet",
    toutesLesPhotos: "All photos",
    par: "By",
  },

  it: {
    chantpro: "ChantPro",
    retour: "← Indietro",
    ajouter: "Aggiungi",
    annuler: "Annulla",
    supprimer: "Elimina",
    modifier: "Modifica",
    fermer: "Chiudi",

    slogan: "Gestisci i tuoi cantieri facilmente",
    commencer: "Inizia gratis",
    chantiers: "Cantieri",
    chantiersDesc: "Segui tutti i tuoi cantieri in tempo reale",
    heures: "Ore",
    heuresDesc: "Monitoraggio semplice per ogni dipendente",
    messagerie: "Messaggistica",
    messagerieDesc: "Comunica con tutta la tua squadra",

    accueil: "Home",
    planning: "Pianificazione",
    messages: "Messaggi",
    photos: "Foto",
    employes: "Dipendenti",

    connexion: "Accedi al tuo spazio",
    emailOuTelephone: "Email (capo) o Telefono (dipendente)",
    motDePasseOuPin: "Password o codice PIN",
    seConnecter: "Accedi",
    commentAppeler: "Come vuoi essere chiamato?",
    erreurConnexion: "Email/telefono o password/PIN errati",

    bonjour: "Ciao",
    chantiersActifs: "Cantieri attivi",
    chantiersEnCours: "Cantieri in corso",
    enCours: "In corso",
    enPause: "In pausa",
    termine: "Completato",

    nouveauChantier: "Nuovo cantiere",
    nomChantier: "Nome del cantiere",
    adresse: "Indirizzo",
    client: "Cliente",
    responsable: "Responsabile",
    raison: "Motivo (opzionale)",
    ajouterChantier: "+ Aggiungi cantiere",
    ajouterUneRaison: "Aggiungi un motivo...",

    nouvelEmploye: "Nuovo dipendente",
    prenom: "Nome",
    nom: "Cognome",
    role: "Ruolo",
    telephone: "Telefono",
    codePin: "Codice PIN (4 cifre)",
    ajouterEmploye: "+ Aggiungi dipendente",
    permissions: "Permessi",
    peutModifierPlanning: "Può modificare la pianificazione",
    peutSupprimerEmployes: "Può eliminare dipendenti",
    peutGererChantiers: "Può gestire i cantieri",

    planningSemaine: "Pianificazione settimanale",
    nouvelleEntree: "Nuova voce",
    choisirEmploye: "Scegli un dipendente",
    choisirChantier: "Scegli un cantiere",
    semainePrecedente: "← Settimana precedente",
    semaineSuivante: "Settimana successiva →",
    revenirAujourdhui: "Torna a oggi",
    prevu: "Previsto",
    realise: "Completato",
    aucuneEntreeJour: "Nessuna voce per questo giorno",
    lundi: "Lunedì",
    mardi: "Martedì",
    mercredi: "Mercoledì",
    jeudi: "Giovedì",
    vendredi: "Venerdì",
    samedi: "Sabato",
    dimanche: "Domenica",

    nouveauMessage: "+ Nuovo messaggio",
    choisirDestinataire: "Scegli un destinatario:",
    ecrireMessage: "Scrivi un messaggio...",
    envoyer: "Invia",
    connecte: "Connesso",
    patron: "Capo",

    galeriePhotos: "📷 Galleria foto",
    aucunePhoto: "Ancora nessuna foto",
    toutesLesPhotos: "Tutte le foto",
    par: "Da",
  },

  ru: {
    chantpro: "ChantPro",
    retour: "← Назад",
    ajouter: "Добавить",
    annuler: "Отмена",
    supprimer: "Удалить",
    modifier: "Изменить",
    fermer: "Закрыть",

    slogan: "Управляйте стройками легко",
    commencer: "Начать бесплатно",
    chantiers: "Объекты",
    chantiersDesc: "Следите за всеми объектами в реальном времени",
    heures: "Часы",
    heuresDesc: "Простой учёт времени для каждого сотрудника",
    messagerie: "Сообщения",
    messagerieDesc: "Общайтесь со всей командой",

    accueil: "Главная",
    planning: "График",
    messages: "Сообщения",
    photos: "Фото",
    employes: "Сотрудники",

    connexion: "Войдите в свой кабинет",
    emailOuTelephone: "Email (руководитель) или Телефон (сотрудник)",
    motDePasseOuPin: "Пароль или PIN-код",
    seConnecter: "Войти",
    commentAppeler: "Как вас называть?",
    erreurConnexion: "Неверный email/телефон или пароль/PIN",

    bonjour: "Привет",
    chantiersActifs: "Активные объекты",
    chantiersEnCours: "Текущие объекты",
    enCours: "В процессе",
    enPause: "На паузе",
    termine: "Завершено",

    nouveauChantier: "Новый объект",
    nomChantier: "Название объекта",
    adresse: "Адрес",
    client: "Клиент",
    responsable: "Ответственный",
    raison: "Причина (необязательно)",
    ajouterChantier: "+ Добавить объект",
    ajouterUneRaison: "Добавить причину...",

    nouvelEmploye: "Новый сотрудник",
    prenom: "Имя",
    nom: "Фамилия",
    role: "Должность",
    telephone: "Телефон",
    codePin: "PIN-код (4 цифры)",
    ajouterEmploye: "+ Добавить сотрудника",
    permissions: "Разрешения",
    peutModifierPlanning: "Может изменять график",
    peutSupprimerEmployes: "Может удалять сотрудников",
    peutGererChantiers: "Может управлять объектами",

    planningSemaine: "Недельный график",
    nouvelleEntree: "Новая запись",
    choisirEmploye: "Выберите сотрудника",
    choisirChantier: "Выберите объект",
    semainePrecedente: "← Предыдущая неделя",
    semaineSuivante: "Следующая неделя →",
    revenirAujourdhui: "Вернуться к сегодня",
    prevu: "Запланировано",
    realise: "Выполнено",
    aucuneEntreeJour: "Нет записей на этот день",
    lundi: "Понедельник",
    mardi: "Вторник",
    mercredi: "Среда",
    jeudi: "Четверг",
    vendredi: "Пятница",
    samedi: "Субота",
    dimanche: "Воскресенье",

    nouveauMessage: "+ Новое сообщение",
    choisirDestinataire: "Выберите получателя:",
    ecrireMessage: "Написать сообщение...",
    envoyer: "Отправить",
    connecte: "Подключен",
    patron: "Руководитель",

    galeriePhotos: "📷 Галерея фото",
    aucunePhoto: "Пока нет фото",
    toutesLesPhotos: "Все фото",
    par: "От",
  },

  pt: {
    chantpro: "ChantPro",
    retour: "← Voltar",
    ajouter: "Adicionar",
    annuler: "Cancelar",
    supprimer: "Excluir",
    modifier: "Editar",
    fermer: "Fechar",

    slogan: "Gerencie seus canteiros facilmente",
    commencer: "Comece gratuitamente",
    chantiers: "Canteiros",
    chantiersDesc: "Acompanhe todos os seus canteiros em tempo real",
    heures: "Horas",
    heuresDesc: "Controle simples de horas para cada funcionário",
    messagerie: "Mensagens",
    messagerieDesc: "Comunique-se com toda a sua equipe",

    accueil: "Início",
    planning: "Cronograma",
    messages: "Mensagens",
    photos: "Fotos",
    employes: "Funcionários",

    connexion: "Entre na sua conta",
    emailOuTelephone: "Email (chefe) ou Telefone (funcionário)",
    motDePasseOuPin: "Senha ou código PIN",
    seConnecter: "Entrar",
    commentAppeler: "Como devemos te chamar?",
    erreurConnexion: "Email/telefone ou senha/PIN incorretos",

    bonjour: "Olá",
    chantiersActifs: "Canteiros ativos",
    chantiersEnCours: "Canteiros em andamento",
    enCours: "Em andamento",
    enPause: "Em pausa",
    termine: "Concluído",

    nouveauChantier: "Novo canteiro",
    nomChantier: "Nome do canteiro",
    adresse: "Endereço",
    client: "Cliente",
    responsable: "Responsável",
    raison: "Motivo (opcional)",
    ajouterChantier: "+ Adicionar canteiro",
    ajouterUneRaison: "Adicionar um motivo...",

    nouvelEmploye: "Novo funcionário",
    prenom: "Nome",
    nom: "Sobrenome",
    role: "Função",
    telephone: "Telefone",
    codePin: "Código PIN (4 dígitos)",
    ajouterEmploye: "+ Adicionar funcionário",
    permissions: "Permissões",
    peutModifierPlanning: "Pode editar o cronograma",
    peutSupprimerEmployes: "Pode excluir funcionários",
    peutGererChantiers: "Pode gerenciar canteiros",

    planningSemaine: "Cronograma semanal",
    nouvelleEntree: "Nova entrada",
    choisirEmploye: "Escolher um funcionário",
    choisirChantier: "Escolher um canteiro",
    semainePrecedente: "← Semana anterior",
    semaineSuivante: "Próxima semana →",
    revenirAujourdhui: "Voltar para hoje",
    prevu: "Planejado",
    realise: "Concluído",
    aucuneEntreeJour: "Nenhuma entrada para este dia",
    lundi: "Segunda-feira",
    mardi: "Terça-feira",
    mercredi: "Quarta-feira",
    jeudi: "Quinta-feira",
    vendredi: "Sexta-feira",
    samedi: "Sábado",
    dimanche: "Domingo",

    nouveauMessage: "+ Nova mensagem",
    choisirDestinataire: "Escolha um destinatário:",
    ecrireMessage: "Escreva uma mensagem...",
    envoyer: "Enviar",
    connecte: "Conectado",
    patron: "Chefe",

    galeriePhotos: "📷 Galeria de fotos",
    aucunePhoto: "Ainda não há fotos",
    toutesLesPhotos: "Todas as fotos",
    par: "Por",
  },
}